config/routes.rb
Uif2012::Application.routes.draw do
  
  resources :guardians

  resources :student_allergies

  resources :households

  resources :students

  resources :groups

  resources :attendences

  resources :locations

  resources :events

  resources :programs

  resources :departments

  resources :registrations



  # Semi-static page routes
  match 'stu_home' => 'students#home', :as => :stu_home
  match 'home' => 'home#home', :as => :home
  #match 'home/jmsg/:msg', :controller => 'home', :action=>'jmsg', :via => :post
  
  root :to => 'home#home'
  
  
end

app/models/attendence.rb
class Attendence < ActiveRecord::Base
  attr_accessible :event_id, :exempt, :student_id
  
  #Relationships
  belongs_to :event
  belongs_to :student
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :active, :description, :name

  #Relationships
  has_many :programs
  validates_presence_of :name
  validates_uniqueness_of :name
  
  scope :alphabetical, order('name')
  scope :active, where('active = ?', true)
  scope :inactive, where('active = ?', false)
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :bibles_distributed, :date, :end_time, :gospel_shared, :meals_served, :program_id, :start_time, :location_id

  #Relationships
  belongs_to :program
  belongs_to :location
  has_many :attendences
    
  #Validations
  validates_date :date
  validates_time :start_time
  validates_time :end_time, :after => :start_time, :allow_blank => true
  validates_numericality_of :location_id, :program_id, :only_integer => true, :greater_than => 0
  validates_numericality_of :meals_served, :only_integer => true, :greater_than_or_equal_to => 0
  #validates_inclusion_of :bibles_distributed, :gospel_shared, :in => [true, false]
    
  #Scopes
  scope :happening_event, where(':start_time IS NOT NULL AND :end_time IS NULL')
  scope :chronological, order(:date, :start_time)
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :active, :max_capacity, :name
  #Relationships
  has_many :registrations
  has_many :programs, :through => :registrations

  #Validations
  validates_presence_of :name
  validates_numericality_of :max_capacity, :greater_than => 1, :message => "must be greater than 1", :allow_nil => true
  
  #validation for sum of max_capacity for team is less than max_capacity of program
  #Scopes
 # scope :program_capacity, join(:registrations, :programs)
  
  #Methods
 # def team_cap_less_than_program_cap
    
 # end
  
end

# def team_cap_less_than_program_cap
#   Team.sum(:max_capacity).where 
 #   x = self.joins(:registrations, :programs)
#    x.sum(:max_capacity).where("registrations.program_id = ?",  
    
 #   lambda {|employee_id| joins(:assignment, :employee).where("assignments.employee_id = ?", employee_id)
 #end
 
 #association is weird - how can a team have many programs

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  attr_accessible :active, :can_text, :cell_phone, :email, :first_name, :guardian_type, :household_id, :last_name


  #Relationships
  belongs_to :household
  # has_many :registrations
  # has_many :programs, :through => :registrations

  #Validations
  validates_presence_of :first_name, :last_name, :guardian_type, :cell_phone


end

app/models/household.rb
class Household < ActiveRecord::Base
  attr_accessible :active, :church, :city, :insurance_company, :insurance_number, :lat, :lon, :name, :street, :street2, :zip


  # Relationships
  has_many :guardians
  has_many :students

  #Validations
  validates_presence_of :name, :street, :city, :zip, :insurance_company
  validates_format_of :zip, :with => /^\d{5}$/, :message => "should be five digits long"
  validates_numericality_of :lat, :lon, :allow_blank => true
  
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :active, :city, :lat, :lon, :name, :street, :zip

  #Relationships
  has_many :events
  has_many :programs, :through => :events

  #Validations
  validates_presence_of :name, :street, :city
  validates_uniqueness_of :name
  validates_format_of :zip, :with => /^\d{5}$/, :message => "should be five digits long"
  validates_numericality_of :lat, :lon, :allow_blank => true
  # Scopes
  scope :alphabetical, order('name')
  scope :active, where('active = ?', true)
  scope :inactive, where('active = ?', false)

end

app/models/program.rb
class Program < ActiveRecord::Base 

  attr_accessible :active, :department_id, :description, :max_capacity, :max_grade, :min_grade, :name

  #Relationships
  belongs_to :department
  has_many :events
  has_many :registrations
  has_many :groups, :through => :registrations
  has_many :locations, :through => :events
  
  #Validations
  validates_presence_of :name, :max_grade, :min_grade, :max_capacity
  validates_uniqueness_of :name
  validates_numericality_of :max_capacity, :max_grade, :min_grade, :only_integer => true, :greater_than => 0, :message => "can only be whole number."
  validates_inclusion_of :max_grade, :min_grade, :in => 1..12, :message => "grades are between 1 and 12"
  validate :max_grade_greater_than_min_grade

  #Methods
  def max_grade_greater_than_min_grade
    errors.add(:max_grade, "must be greater than min grade") unless self.max_grade.to_i > self.min_grade.to_i
  end


end

app/models/registration.rb
class Registration < ActiveRecord::Base
  attr_accessible :program_id, :student_id, :group_id

  #Relationships
  belongs_to :group
  belongs_to :program
  belongs_to :student
  
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :barcode_number, :can_text, :cell_phone, :date_of_birth, :email, :first_name, :grade, :household_id, :is_male, :last_name, :photo, :status

  #Relationships
  belongs_to :household
  has_many :attendances
  has_many :registrations
  has_many :student_allergies

  #Validations
  validates_presence_of :first_name, :last_name, :is_male, :grade, :date_of_birth, :cell_phone
  validates :date_of_birth, :timeliness => {:on_or_before => lambda { Date.current }, :type => :date}
end

app/models/student_allergy.rb
class StudentAllergy < ActiveRecord::Base
  attr_accessible :allergy_id, :student_id
  
  belongs_to :allergy
  belongs_to :student
  
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :active, :max_capacity, :name
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/guardians_helper.rb
module GuardiansHelper
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br />
    <%= f.number_field :department_id %>
  </div>
  <div class="field">
    <%= f.label :min_grade %><br />
    <%= f.number_field :min_grade %>
  </div>
  <div class="field">
    <%= f.label :max_grade %><br />
    <%= f.number_field :max_grade %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :max_capacity %><br />
    <%= f.number_field :max_capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Department</th>
    <th>Min grade</th>
    <th>Max grade</th>
    <th>Active</th>
    <th>Max capacity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programs.each do |program| %>
  <tr>
    <td><%= program.name %></td>
    <td><%= program.description %></td>
    <td><%= program.department_id %></td>
    <td><%= program.min_grade %></td>
    <td><%= program.max_grade %></td>
    <td><%= program.active %></td>
    <td><%= program.max_capacity %></td>
    <td><%= link_to 'Show', program %></td>
    <td><%= link_to 'Edit', edit_program_path(program) %></td>
    <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @program.name %>
</p>

<p>
  <b>Description:</b>
  <%= @program.description %>
</p>

<p>
  <b>Department:</b>
  <%= @program.department_id %>
</p>

<p>
  <b>Min grade:</b>
  <%= @program.min_grade %>
</p>

<p>
  <b>Max grade:</b>
  <%= @program.max_grade %>
</p>

<p>
  <b>Active:</b>
  <%= @program.active %>
</p>

<p>
  <b>Max capacity:</b>
  <%= @program.max_capacity %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>