config/routes.rb
Uif2012::Application.routes.draw do
  
  resources :guardians

  resources :student_allergies

  resources :households

  resources :students

  resources :groups

  resources :attendences

  resources :locations

  resources :events

  resources :programs

  resources :departments

  resources :registrations



  # Semi-static page routes
  match 'stu_home' => 'students#home', :as => :stu_home
  match 'home' => 'home#home', :as => :home
  #match 'home/jmsg/:msg', :controller => 'home', :action=>'jmsg', :via => :post
  
  root :to => 'home#home'
  
  
end

app/models/student_allergy.rb
class StudentAllergy < ActiveRecord::Base
  attr_accessible :allergy_id, :student_id
  
  belongs_to :allergy
  belongs_to :student
  
end

app/controllers/student_allergies_controller.rb
class StudentAllergiesController < ApplicationController
  # GET /student_allergies
  # GET /student_allergies.json
  def index
    @student_allergies = StudentAllergy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_allergies }
    end
  end

  # GET /student_allergies/1
  # GET /student_allergies/1.json
  def show
    @student_allergy = StudentAllergy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_allergy }
    end
  end

  # GET /student_allergies/new
  # GET /student_allergies/new.json
  def new
    @student_allergy = StudentAllergy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_allergy }
    end
  end

  # GET /student_allergies/1/edit
  def edit
    @student_allergy = StudentAllergy.find(params[:id])
  end

  # POST /student_allergies
  # POST /student_allergies.json
  def create
    @student_allergy = StudentAllergy.new(params[:student_allergy])

    respond_to do |format|
      if @student_allergy.save
        format.html { redirect_to @student_allergy, notice: 'Student allergy was successfully created.' }
        format.json { render json: @student_allergy, status: :created, location: @student_allergy }
      else
        format.html { render action: "new" }
        format.json { render json: @student_allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_allergies/1
  # PUT /student_allergies/1.json
  def update
    @student_allergy = StudentAllergy.find(params[:id])

    respond_to do |format|
      if @student_allergy.update_attributes(params[:student_allergy])
        format.html { redirect_to @student_allergy, notice: 'Student allergy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_allergies/1
  # DELETE /student_allergies/1.json
  def destroy
    @student_allergy = StudentAllergy.find(params[:id])
    @student_allergy.destroy

    respond_to do |format|
      format.html { redirect_to student_allergies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/student_allergies_helper.rb
module StudentAllergiesHelper
end

app/views/student_allergies/_form.html.erb
<%= form_for(@student_allergy) do |f| %>
  <% if @student_allergy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_allergy.errors.count, "error") %> prohibited this student_allergy from being saved:</h2>

      <ul>
      <% @student_allergy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :allergy_id %><br />
    <%= f.number_field :allergy_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_allergies/edit.html.erb
<h1>Editing student_allergy</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_allergy %> |
<%= link_to 'Back', student_allergies_path %>

app/views/student_allergies/index.html.erb
<h1>Listing student_allergies</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Allergy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_allergies.each do |student_allergy| %>
  <tr>
    <td><%= student_allergy.student_id %></td>
    <td><%= student_allergy.allergy_id %></td>
    <td><%= link_to 'Show', student_allergy %></td>
    <td><%= link_to 'Edit', edit_student_allergy_path(student_allergy) %></td>
    <td><%= link_to 'Destroy', student_allergy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student allergy', new_student_allergy_path %>

app/views/student_allergies/new.html.erb
<h1>New student_allergy</h1>

<%= render 'form' %>

<%= link_to 'Back', student_allergies_path %>

app/views/student_allergies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @student_allergy.student_id %>
</p>

<p>
  <b>Allergy:</b>
  <%= @student_allergy.allergy_id %>
</p>


<%= link_to 'Edit', edit_student_allergy_path(@student_allergy) %> |
<%= link_to 'Back', student_allergies_path %>