config/routes.rb
Uif2012::Application.routes.draw do
  
  resources :guardians

  resources :student_allergies

  resources :households

  resources :students

  resources :groups

  resources :attendences

  resources :locations

  resources :events

  resources :programs

  resources :departments

  resources :registrations



  # Semi-static page routes
  match 'stu_home' => 'students#home', :as => :stu_home
  match 'home' => 'home#home', :as => :home
  #match 'home/jmsg/:msg', :controller => 'home', :action=>'jmsg', :via => :post
  
  root :to => 'home#home'
  
  
end

app/models/attendence.rb
class Attendence < ActiveRecord::Base
  attr_accessible :event_id, :exempt, :student_id
  
  #Relationships
  belongs_to :event
  belongs_to :student
end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController
  # GET /attendences
  # GET /attendences.json
  def index
    @attendences = Attendence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendences }
    end
  end

  # GET /attendences/1
  # GET /attendences/1.json
  def show
    @attendence = Attendence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendence }
    end
  end

  # GET /attendences/new
  # GET /attendences/new.json
  def new
    @attendence = Attendence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendence }
    end
  end

  # GET /attendences/1/edit
  def edit
    @attendence = Attendence.find(params[:id])
  end

  # POST /attendences
  # POST /attendences.json
  def create
    @attendence = Attendence.new(params[:attendence])

    respond_to do |format|
      if @attendence.save
        format.html { redirect_to @attendence, notice: 'Attendence was successfully created.' }
        format.json { render json: @attendence, status: :created, location: @attendence }
      else
        format.html { render action: "new" }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendences/1
  # PUT /attendences/1.json
  def update
    @attendence = Attendence.find(params[:id])

    respond_to do |format|
      if @attendence.update_attributes(params[:attendence])
        format.html { redirect_to @attendence, notice: 'Attendence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendences/1
  # DELETE /attendences/1.json
  def destroy
    @attendence = Attendence.find(params[:id])
    @attendence.destroy

    respond_to do |format|
      format.html { redirect_to attendences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/views/attendences/_form.html.erb
<%= form_for(@attendence) do |f| %>
  <% if @attendence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendence.errors.count, "error") %> prohibited this attendence from being saved:</h2>

      <ul>
      <% @attendence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :exempt %><br />
    <%= f.check_box :exempt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendences/edit.html.erb
<h1>Editing attendence</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendence %> |
<%= link_to 'Back', attendences_path %>

app/views/attendences/index.html.erb
<h1>Listing attendences</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Event</th>
    <th>Exempt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendences.each do |attendence| %>
  <tr>
    <td><%= attendence.student_id %></td>
    <td><%= attendence.event_id %></td>
    <td><%= attendence.exempt %></td>
    <td><%= link_to 'Show', attendence %></td>
    <td><%= link_to 'Edit', edit_attendence_path(attendence) %></td>
    <td><%= link_to 'Destroy', attendence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendence', new_attendence_path %>

app/views/attendences/new.html.erb
<h1>New attendence</h1>

<%= render 'form' %>

<%= link_to 'Back', attendences_path %>

app/views/attendences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @attendence.student_id %>
</p>

<p>
  <b>Event:</b>
  <%= @attendence.event_id %>
</p>

<p>
  <b>Exempt:</b>
  <%= @attendence.exempt %>
</p>


<%= link_to 'Edit', edit_attendence_path(@attendence) %> |
<%= link_to 'Back', attendences_path %>