config/routes.rb
Uif2012::Application.routes.draw do
  
  resources :guardians

  resources :student_allergies

  resources :households

  resources :students

  resources :groups

  resources :attendences

  resources :locations

  resources :events

  resources :programs

  resources :departments

  resources :registrations



  # Semi-static page routes
  match 'stu_home' => 'students#home', :as => :stu_home
  match 'home' => 'home#home', :as => :home
  #match 'home/jmsg/:msg', :controller => 'home', :action=>'jmsg', :via => :post
  
  root :to => 'home#home'
  
  
end

app/models/household.rb
class Household < ActiveRecord::Base
  attr_accessible :active, :church, :city, :insurance_company, :insurance_number, :lat, :lon, :name, :street, :street2, :zip


  # Relationships
  has_many :guardians
  has_many :students

  #Validations
  validates_presence_of :name, :street, :city, :zip, :insurance_company
  validates_format_of :zip, :with => /^\d{5}$/, :message => "should be five digits long"
  validates_numericality_of :lat, :lon, :allow_blank => true
  
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  # GET /households
  # GET /households.json
  def index
    @households = Household.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @households }
    end
  end

  # GET /households/1
  # GET /households/1.json
  def show
    @household = Household.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @household }
    end
  end

  # GET /households/new
  # GET /households/new.json
  def new
    @household = Household.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @household }
    end
  end

  # GET /households/1/edit
  def edit
    @household = Household.find(params[:id])
  end

  # POST /households
  # POST /households.json
  def create
    @household = Household.new(params[:household])

    respond_to do |format|
      if @household.save
        format.html { redirect_to @household, notice: 'Household was successfully created.' }
        format.json { render json: @household, status: :created, location: @household }
      else
        format.html { render action: "new" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /households/1
  # PUT /households/1.json
  def update
    @household = Household.find(params[:id])

    respond_to do |format|
      if @household.update_attributes(params[:household])
        format.html { redirect_to @household, notice: 'Household was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /households/1
  # DELETE /households/1.json
  def destroy
    @household = Household.find(params[:id])
    @household.destroy

    respond_to do |format|
      format.html { redirect_to households_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/views/households/_form.html.erb
<%= form_for(@household) do |f| %>
  <% if @household.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@household.errors.count, "error") %> prohibited this household from being saved:</h2>

      <ul>
      <% @household.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :street2 %><br />
    <%= f.text_field :street2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :insurance_company %><br />
    <%= f.text_field :insurance_company %>
  </div>
  <div class="field">
    <%= f.label :insurance_number %><br />
    <%= f.text_field :insurance_number %>
  </div>
  <div class="field">
    <%= f.label :church %><br />
    <%= f.text_field :church %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/households/edit.html.erb
<h1>Editing household</h1>

<%= render 'form' %>

<%= link_to 'Show', @household %> |
<%= link_to 'Back', households_path %>

app/views/households/index.html.erb
<h1>Listing households</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Street</th>
    <th>Street2</th>
    <th>City</th>
    <th>Zip</th>
    <th>Insurance company</th>
    <th>Insurance number</th>
    <th>Church</th>
    <th>Lat</th>
    <th>Lon</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @households.each do |household| %>
  <tr>
    <td><%= household.name %></td>
    <td><%= household.street %></td>
    <td><%= household.street2 %></td>
    <td><%= household.city %></td>
    <td><%= household.zip %></td>
    <td><%= household.insurance_company %></td>
    <td><%= household.insurance_number %></td>
    <td><%= household.church %></td>
    <td><%= household.lat %></td>
    <td><%= household.lon %></td>
    <td><%= household.active %></td>
    <td><%= link_to 'Show', household %></td>
    <td><%= link_to 'Edit', edit_household_path(household) %></td>
    <td><%= link_to 'Destroy', household, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Household', new_household_path %>

app/views/households/new.html.erb
<h1>New household</h1>

<%= render 'form' %>

<%= link_to 'Back', households_path %>

app/views/households/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @household.name %>
</p>

<p>
  <b>Street:</b>
  <%= @household.street %>
</p>

<p>
  <b>Street2:</b>
  <%= @household.street2 %>
</p>

<p>
  <b>City:</b>
  <%= @household.city %>
</p>

<p>
  <b>Zip:</b>
  <%= @household.zip %>
</p>

<p>
  <b>Insurance company:</b>
  <%= @household.insurance_company %>
</p>

<p>
  <b>Insurance number:</b>
  <%= @household.insurance_number %>
</p>

<p>
  <b>Church:</b>
  <%= @household.church %>
</p>

<p>
  <b>Lat:</b>
  <%= @household.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @household.lon %>
</p>

<p>
  <b>Active:</b>
  <%= @household.active %>
</p>


<%= link_to 'Edit', edit_household_path(@household) %> |
<%= link_to 'Back', households_path %>